In [1]:
from datascience import *

In [2]:
Table()  # empty table

In [3]:
Table().with_column('Name', make_array('Lawton', 'Lonzo', 'Bill'))

Name
Lawton
Lonzo
Bill


In [4]:
Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'), 
    'Age', make_array(33, 6, 34)
)

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [5]:
people = Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'), 
    'Age', make_array(33, 6, 34)
)

In [6]:
people

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [8]:
# It's fine to use the plural with_columns and only add a single column
people.with_columns('Employer', make_array("CCC", 'Unemployed', 'CCC'))

Name,Age,Employer
Lawton,33,CCC
Lonzo,6,Unemployed
Bill,34,CCC


In [10]:
people  # didn't change

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [11]:
people.relabeled('Age', 'Trips around the sun')

Name,Trips around the sun
Lawton,33
Lonzo,6
Bill,34


In [12]:
people

Name,Age
Lawton,33
Lonzo,6
Bill,34


---

In [14]:
cones = Table.read_table('data/cones.csv')
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [15]:
cones.num_columns

3

In [16]:
cones.num_rows

7

In [17]:
cones.labels

('Flavor', 'Color', 'Price')

In [18]:
cones.column('Price')

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [19]:
cones.column(2)

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [20]:
cones.column('Price').item(3)

3.5

In [21]:
cones.column('Price').item(0)  # first one is at index 0

3.55

In [26]:
# Crushed ICE: calculate the total price after applying 8.75% sales tax to Price column

In [27]:
# option 1
tax = cones.column('Price') * (8.75 / 100)
tax + cones.column('Price')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [30]:
# option 2
import numpy as np
np.round(cones.column('Price') * 1.0875, 2)

array([ 3.86,  5.17,  5.71,  3.81,  5.71,  5.71,  5.17])

In [35]:
tax_rate = 0.0875
tax = cones.column('Price') * tax_rate
cones_with_tax = cones.with_column('Price with tax', tax + cones.column('Price'))
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,3.86062
chocolate,light brown,4.75,5.16563
chocolate,dark brown,5.25,5.70937
vanilla,white,3.5,3.80625
strawberry,pink,5.25,5.70937
chocolate,dark brown,5.25,5.70937
bubblegum,pink,4.75,5.16563


In [38]:
cones_with_tax.set_format('Price with tax', CurrencyFormatter)

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [40]:
cones_with_tax.column('Price with tax')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [42]:
Table().with_column('x', make_array(1000, 100000, 9999999999999)).set_format('x', NumberFormatter)

x
"1,000"
"100,000"
"9,999,999,999,999"


In [44]:
Table().with_column('x', make_array(0.5, 0.75, 0.9999)).set_format('x', PercentFormatter)

x
50.00%
75.00%
99.99%


In [46]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [47]:
cones_with_tax.select('Flavor', 'Price with tax')

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [48]:
cones_with_tax.select(0, 3)  # indices work too

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [49]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum


In [50]:
cones.column('Flavor') # only this one makes an array!

array(['strawberry', 'chocolate', 'chocolate', 'vanilla', 'strawberry',
       'chocolate', 'bubblegum'],
      dtype='<U10')

In [52]:
cones_with_tax.drop('Price') # makes a new Table, as usual

Flavor,Color,Price with tax
strawberry,pink,$3.86
chocolate,light brown,$5.17
chocolate,dark brown,$5.71
vanilla,white,$3.81
strawberry,pink,$5.71
chocolate,dark brown,$5.71
bubblegum,pink,$5.17


In [55]:
cones_with_tax.sort('Price with tax', descending=True)

Flavor,Color,Price,Price with tax
chocolate,dark brown,5.25,$5.71
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
chocolate,light brown,4.75,$5.17
bubblegum,pink,4.75,$5.17
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [56]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [57]:
cones_with_tax.take(4)

Flavor,Color,Price,Price with tax
strawberry,pink,5.25,$5.71


In [58]:
cones_with_tax.take(1, 3, 5)

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [62]:
import numpy as np
cones_with_tax.take(np.arange(1, cones_with_tax.num_rows, 2))  # all the odd indices

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [63]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [64]:
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [65]:
cones = cones_with_tax  # remember that you can always overwrite an existing Table!

In [66]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [67]:
cones.where('Flavor', are.equal_to('chocolate'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [68]:
# by default, you get an equality check. This is equivalent to the line above!
cones.where('Flavor', 'chocolate') # this is shorthand for the one above

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [69]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [70]:
cones.where('Price with tax', are.below_or_equal_to(5))

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [71]:
cones.where('Price with tax', are.below_or_equal_to(5)).sort('Price with tax')

Flavor,Color,Price,Price with tax
vanilla,white,3.5,$3.81
strawberry,pink,3.55,$3.86


In [72]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [73]:
cones.where('Color', are.containing('brown'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [74]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [75]:
cones.show(3)  # shows the first 3 rows. .show() with nothing shows everything!

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71


---

In [76]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water,attack,base_egg_steps,base_happiness,base_total,capture_rate,classfication,defense,experience_growth,height_m,hp,japanese_name,name,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,49,5120,70,318,45,Seed Pokémon,49,1059860,0.7,45,Fushigidaneフシギダネ,Bulbasaur,88.1,1,65,65,45,grass,poison,6.9,1,0
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,62,5120,70,405,45,Seed Pokémon,63,1059860,1,60,Fushigisouフシギソウ,Ivysaur,88.1,2,80,80,60,grass,poison,13,1,0
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,100,5120,70,625,45,Seed Pokémon,123,1059860,2,80,Fushigibanaフシギバナ,Venusaur,88.1,3,122,120,80,grass,poison,100,1,0
"['Blaze', 'Solar Power']",0.5,1,1,1,0.5,1,0.5,1,1,0.5,2,0.5,1,1,1,2,0.5,2,52,5120,70,309,45,Lizard Pokémon,43,1059860,0.6,39,Hitokageヒトカゲ,Charmander,88.1,4,60,50,65,fire,nan,8.5,1,0
"['Blaze', 'Solar Power']",0.5,1,1,1,0.5,1,0.5,1,1,0.5,2,0.5,1,1,1,2,0.5,2,64,5120,70,405,45,Flame Pokémon,58,1059860,1.1,58,Lizardoリザード,Charmeleon,88.1,5,80,65,80,fire,nan,19,1,0
"['Blaze', 'Solar Power']",0.25,1,1,2,0.5,0.5,0.5,1,1,0.25,0,1,1,1,1,4,0.5,2,104,5120,70,634,45,Flame Pokémon,78,1059860,1.7,78,Lizardonリザードン,Charizard,88.1,6,159,115,100,fire,flying,90.5,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,48,5120,70,314,45,Tiny Turtle Pokémon,65,1059860,0.5,44,Zenigameゼニガメ,Squirtle,88.1,7,50,64,43,water,nan,9,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,63,5120,70,405,45,Turtle Pokémon,80,1059860,1,59,Kameilカメール,Wartortle,88.1,8,65,80,58,water,nan,22.5,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,103,5120,70,630,45,Shellfish Pokémon,120,1059860,1.6,79,Kamexカメックス,Blastoise,88.1,9,135,115,78,water,nan,85.5,1,0
"['Shield Dust', 'Run Away']",1,1,1,1,1,0.5,2,2,1,0.5,0.5,1,1,1,1,2,1,1,30,3840,70,195,255,Worm Pokémon,35,1000000,0.3,45,Caterpieキャタピー,Caterpie,50,10,20,20,45,bug,nan,2.9,1,0


In [89]:
summed_values = pokemon.column('against_bug') + pokemon.column('against_dark') + pokemon.column('against_dragon') + pokemon.column('against_electric') + pokemon.column('against_fairy') + pokemon.column('against_fight') + pokemon.column('against_fire') + pokemon.column('against_flying') + pokemon.column('against_ghost') + pokemon.column('against_grass') + pokemon.column('against_ground') + pokemon.column('against_ice') + pokemon.column('against_normal') + pokemon.column('against_poison') + pokemon.column('against_psychic') + pokemon.column('against_rock') + pokemon.column('against_steel') + pokemon.column('against_water')
pokemon.select('name', 'type1', 'type2', 'generation').with_column('loser rating', summed_values).sort('loser rating', descending=True).show(25)

name,type1,type2,generation,loser rating
Amaura,rock,ice,6,26
Aurorus,rock,ice,6,26
Paras,bug,grass,1,25
Parasect,bug,grass,1,25
Wormadam,bug,grass,4,25
Snover,grass,ice,4,25
Abomasnow,grass,ice,4,25
Sewaddle,bug,grass,5,25
Swadloon,bug,grass,5,25
Leavanny,bug,grass,5,25


In [92]:
temp = pokemon.select('name', 'is_legendary', 'generation')
temp

name,is_legendary,generation
Bulbasaur,0,1
Ivysaur,0,1
Venusaur,0,1
Charmander,0,1
Charmeleon,0,1
Charizard,0,1
Squirtle,0,1
Wartortle,0,1
Blastoise,0,1
Caterpie,0,1


In [94]:
gen1 = temp.where('generation', are.equal_to(1))
gen1.num_rows

151

In [98]:
gen1.where('is_legendary', 1).num_rows / gen1.num_rows

0.033112582781456956

In [101]:
which_gen = 2
gen = temp.where('generation', which_gen)
gen.where('is_legendary', 1).num_rows / gen.num_rows

0.06

In [102]:
which_gen = 3
gen = temp.where('generation', which_gen)
gen.where('is_legendary', 1).num_rows / gen.num_rows

0.07407407407407407

In [108]:
temp = pokemon.select('name', 'height_m')
temp.show(25)

name,height_m
Bulbasaur,0.7
Ivysaur,1
Venusaur,2
Charmander,0.6
Charmeleon,1.1
Charizard,1.7
Squirtle,0.5
Wartortle,1
Blastoise,1.6
Caterpie,0.3


In [109]:
temp.where('height_m', are.above_or_equal_to(0)).sort('height_m', descending=True).show(5)

name,height_m
Wailord,14.5
Steelix,9.2
Celesteela,9.2
Onix,8.8
Rayquaza,7


In [113]:
temp = pokemon.select('name', 'speed', 'weight_kg').with_column(
    'speed/weight ratio', pokemon.column('speed') / pokemon.column('weight_kg')
)
temp

name,speed,weight_kg,speed/weight ratio
Bulbasaur,45,6.9,6.52174
Ivysaur,60,13,4.61538
Venusaur,80,100,0.8
Charmander,65,8.5,7.64706
Charmeleon,80,19,4.21053
Charizard,100,90.5,1.10497
Squirtle,43,9,4.77778
Wartortle,58,22.5,2.57778
Blastoise,78,85.5,0.912281
Caterpie,45,2.9,15.5172


In [115]:
# nan is short for "not a number". It's a value that is a placeholder for "I don't know"
# you can use .where to get rid of nans
temp.where(3, are.above_or_equal_to(0)).sort(3, descending=True)

name,speed,weight_kg,speed/weight ratio
Kartana,109,0.1,1090
Haunter,95,0.1,950
Gastly,80,0.1,800
Flabébé,42,0.1,420
Cutiefly,84,0.2,420
Azelf,115,0.3,383.333
Cosmog,37,0.1,370
Comfey,100,0.3,333.333
Uxie,95,0.3,316.667
Rotom,86,0.3,286.667


In [117]:
# question: how does the speed of pokemon that are more likely to be female
# compare to the speed of pokemon that are more likely to be male?
temp = pokemon.select('name', 'percentage_male', 'speed')
temp

name,percentage_male,speed
Bulbasaur,88.1,45
Ivysaur,88.1,60
Venusaur,88.1,80
Charmander,88.1,65
Charmeleon,88.1,80
Charizard,88.1,100
Squirtle,88.1,43
Wartortle,88.1,58
Blastoise,88.1,78
Caterpie,50,45


In [119]:
temp = temp.with_column('percentage_female', 100 - temp.column('percentage_male'))
temp

name,percentage_male,speed,percentage_female
Bulbasaur,88.1,45,11.9
Ivysaur,88.1,60,11.9
Venusaur,88.1,80,11.9
Charmander,88.1,65,11.9
Charmeleon,88.1,80,11.9
Charizard,88.1,100,11.9
Squirtle,88.1,43,11.9
Wartortle,88.1,58,11.9
Blastoise,88.1,78,11.9
Caterpie,50,45,50


In [120]:
temp.where('percentage_female', are.above(50))

name,percentage_male,speed,percentage_female
Nidoran♀,0,41,100
Nidorina,0,56,100
Nidoqueen,0,76,100
Clefairy,24.6,35,75.4
Clefable,24.6,60,75.4
Vulpix,24.6,65,75.4
Ninetales,24.6,109,75.4
Jigglypuff,24.6,20,75.4
Wigglytuff,24.6,45,75.4
Chansey,0,50,100


In [122]:
temp.where('percentage_female', are.above(50)).column('speed').mean()

66.79245283018868

In [123]:
temp.where('percentage_male', are.above(50)).column('speed').mean()

68.953020134228183