In [1]:
from datascience import *

In [2]:
Table()  # empty table

In [3]:
Table().with_column('Name', make_array('Lawton', 'Lonzo', 'Bill'))

Name
Lawton
Lonzo
Bill


In [4]:
Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'), 
    'Age', make_array(33, 6, 34)
)

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [5]:
people = Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'), 
    'Age', make_array(33, 6, 34)
)

In [6]:
people

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [8]:
# It's fine to use the plural with_columns and only add a single column
people.with_columns('Employer', make_array("CCC", 'Unemployed', 'CCC'))

Name,Age,Employer
Lawton,33,CCC
Lonzo,6,Unemployed
Bill,34,CCC


In [10]:
people  # didn't change

Name,Age
Lawton,33
Lonzo,6
Bill,34


In [11]:
people.relabeled('Age', 'Trips around the sun')

Name,Trips around the sun
Lawton,33
Lonzo,6
Bill,34


In [12]:
people

Name,Age
Lawton,33
Lonzo,6
Bill,34


---

In [14]:
cones = Table.read_table('data/cones.csv')
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [15]:
cones.num_columns

3

In [16]:
cones.num_rows

7

In [17]:
cones.labels

('Flavor', 'Color', 'Price')

In [18]:
cones.column('Price')

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [19]:
cones.column(2)

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [20]:
cones.column('Price').item(3)

3.5

In [21]:
cones.column('Price').item(0)  # first one is at index 0

3.55

In [26]:
# Crushed ICE: calculate the total price after applying 8.75% sales tax to Price column

In [27]:
# option 1
tax = cones.column('Price') * (8.75 / 100)
tax + cones.column('Price')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [30]:
# option 2
import numpy as np
np.round(cones.column('Price') * 1.0875, 2)

array([ 3.86,  5.17,  5.71,  3.81,  5.71,  5.71,  5.17])

In [35]:
tax_rate = 0.0875
tax = cones.column('Price') * tax_rate
cones_with_tax = cones.with_column('Price with tax', tax + cones.column('Price'))
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,3.86062
chocolate,light brown,4.75,5.16563
chocolate,dark brown,5.25,5.70937
vanilla,white,3.5,3.80625
strawberry,pink,5.25,5.70937
chocolate,dark brown,5.25,5.70937
bubblegum,pink,4.75,5.16563


In [38]:
cones_with_tax.set_format('Price with tax', CurrencyFormatter)

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [40]:
cones_with_tax.column('Price with tax')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [42]:
Table().with_column('x', make_array(1000, 100000, 9999999999999)).set_format('x', NumberFormatter)

x
"1,000"
"100,000"
"9,999,999,999,999"


In [44]:
Table().with_column('x', make_array(0.5, 0.75, 0.9999)).set_format('x', PercentFormatter)

x
50.00%
75.00%
99.99%


In [46]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [47]:
cones_with_tax.select('Flavor', 'Price with tax')

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [48]:
cones_with_tax.select(0, 3)  # indices work too

Flavor,Price with tax
strawberry,$3.86
chocolate,$5.17
chocolate,$5.71
vanilla,$3.81
strawberry,$5.71
chocolate,$5.71
bubblegum,$5.17


In [49]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum


In [50]:
cones.column('Flavor') # only this one makes an array!

array(['strawberry', 'chocolate', 'chocolate', 'vanilla', 'strawberry',
       'chocolate', 'bubblegum'],
      dtype='<U10')

In [52]:
cones_with_tax.drop('Price') # makes a new Table, as usual

Flavor,Color,Price with tax
strawberry,pink,$3.86
chocolate,light brown,$5.17
chocolate,dark brown,$5.71
vanilla,white,$3.81
strawberry,pink,$5.71
chocolate,dark brown,$5.71
bubblegum,pink,$5.17


In [55]:
cones_with_tax.sort('Price with tax', descending=True)

Flavor,Color,Price,Price with tax
chocolate,dark brown,5.25,$5.71
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
chocolate,light brown,4.75,$5.17
bubblegum,pink,4.75,$5.17
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [56]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [57]:
cones_with_tax.take(4)

Flavor,Color,Price,Price with tax
strawberry,pink,5.25,$5.71


In [58]:
cones_with_tax.take(1, 3, 5)

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [62]:
import numpy as np
cones_with_tax.take(np.arange(1, cones_with_tax.num_rows, 2))  # all the odd indices

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
vanilla,white,3.5,$3.81
chocolate,dark brown,5.25,$5.71


In [63]:
cones_with_tax

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [64]:
cones

Flavor,Color,Price
strawberry,pink,3.55
chocolate,light brown,4.75
chocolate,dark brown,5.25
vanilla,white,3.5
strawberry,pink,5.25
chocolate,dark brown,5.25
bubblegum,pink,4.75


In [65]:
cones = cones_with_tax  # remember that you can always overwrite an existing Table!

In [66]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [67]:
cones.where('Flavor', are.equal_to('chocolate'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [68]:
# by default, you get an equality check. This is equivalent to the line above!
cones.where('Flavor', 'chocolate') # this is shorthand for the one above

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [69]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [70]:
cones.where('Price with tax', are.below_or_equal_to(5))

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
vanilla,white,3.5,$3.81


In [71]:
cones.where('Price with tax', are.below_or_equal_to(5)).sort('Price with tax')

Flavor,Color,Price,Price with tax
vanilla,white,3.5,$3.81
strawberry,pink,3.55,$3.86


In [72]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [73]:
cones.where('Color', are.containing('brown'))

Flavor,Color,Price,Price with tax
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
chocolate,dark brown,5.25,$5.71


In [74]:
cones

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71
vanilla,white,3.5,$3.81
strawberry,pink,5.25,$5.71
chocolate,dark brown,5.25,$5.71
bubblegum,pink,4.75,$5.17


In [75]:
cones.show(3)  # shows the first 3 rows. .show() with nothing shows everything!

Flavor,Color,Price,Price with tax
strawberry,pink,3.55,$3.86
chocolate,light brown,4.75,$5.17
chocolate,dark brown,5.25,$5.71


---

In [76]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water,attack,base_egg_steps,base_happiness,base_total,capture_rate,classfication,defense,experience_growth,height_m,hp,japanese_name,name,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,49,5120,70,318,45,Seed Pokémon,49,1059860,0.7,45,Fushigidaneフシギダネ,Bulbasaur,88.1,1,65,65,45,grass,poison,6.9,1,0
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,62,5120,70,405,45,Seed Pokémon,63,1059860,1,60,Fushigisouフシギソウ,Ivysaur,88.1,2,80,80,60,grass,poison,13,1,0
"['Overgrow', 'Chlorophyll']",1,1,1,0.5,0.5,0.5,2,2,1,0.25,1,2,1,1,2,1,1,0.5,100,5120,70,625,45,Seed Pokémon,123,1059860,2,80,Fushigibanaフシギバナ,Venusaur,88.1,3,122,120,80,grass,poison,100,1,0
"['Blaze', 'Solar Power']",0.5,1,1,1,0.5,1,0.5,1,1,0.5,2,0.5,1,1,1,2,0.5,2,52,5120,70,309,45,Lizard Pokémon,43,1059860,0.6,39,Hitokageヒトカゲ,Charmander,88.1,4,60,50,65,fire,nan,8.5,1,0
"['Blaze', 'Solar Power']",0.5,1,1,1,0.5,1,0.5,1,1,0.5,2,0.5,1,1,1,2,0.5,2,64,5120,70,405,45,Flame Pokémon,58,1059860,1.1,58,Lizardoリザード,Charmeleon,88.1,5,80,65,80,fire,nan,19,1,0
"['Blaze', 'Solar Power']",0.25,1,1,2,0.5,0.5,0.5,1,1,0.25,0,1,1,1,1,4,0.5,2,104,5120,70,634,45,Flame Pokémon,78,1059860,1.7,78,Lizardonリザードン,Charizard,88.1,6,159,115,100,fire,flying,90.5,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,48,5120,70,314,45,Tiny Turtle Pokémon,65,1059860,0.5,44,Zenigameゼニガメ,Squirtle,88.1,7,50,64,43,water,nan,9,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,63,5120,70,405,45,Turtle Pokémon,80,1059860,1,59,Kameilカメール,Wartortle,88.1,8,65,80,58,water,nan,22.5,1,0
"['Torrent', 'Rain Dish']",1,1,1,2,1,1,0.5,1,1,2,1,0.5,1,1,1,1,0.5,0.5,103,5120,70,630,45,Shellfish Pokémon,120,1059860,1.6,79,Kamexカメックス,Blastoise,88.1,9,135,115,78,water,nan,85.5,1,0
"['Shield Dust', 'Run Away']",1,1,1,1,1,0.5,2,2,1,0.5,0.5,1,1,1,1,2,1,1,30,3840,70,195,255,Worm Pokémon,35,1000000,0.3,45,Caterpieキャタピー,Caterpie,50,10,20,20,45,bug,nan,2.9,1,0


In [89]:
summed_values = pokemon.column('against_bug') + pokemon.column('against_dark') + pokemon.column('against_dragon') + pokemon.column('against_electric') + pokemon.column('against_fairy') + pokemon.column('against_fight') + pokemon.column('against_fire') + pokemon.column('against_flying') + pokemon.column('against_ghost') + pokemon.column('against_grass') + pokemon.column('against_ground') + pokemon.column('against_ice') + pokemon.column('against_normal') + pokemon.column('against_poison') + pokemon.column('against_psychic') + pokemon.column('against_rock') + pokemon.column('against_steel') + pokemon.column('against_water')
pokemon.select('name', 'type1', 'type2', 'generation').with_column('loser rating', summed_values).sort('loser rating', descending=True).show(25)

name,type1,type2,generation,loser rating
Amaura,rock,ice,6,26
Aurorus,rock,ice,6,26
Paras,bug,grass,1,25
Parasect,bug,grass,1,25
Wormadam,bug,grass,4,25
Snover,grass,ice,4,25
Abomasnow,grass,ice,4,25
Sewaddle,bug,grass,5,25
Swadloon,bug,grass,5,25
Leavanny,bug,grass,5,25


In [92]:
temp = pokemon.select('name', 'is_legendary', 'generation')
temp

name,is_legendary,generation
Bulbasaur,0,1
Ivysaur,0,1
Venusaur,0,1
Charmander,0,1
Charmeleon,0,1
Charizard,0,1
Squirtle,0,1
Wartortle,0,1
Blastoise,0,1
Caterpie,0,1


In [94]:
gen1 = temp.where('generation', are.equal_to(1))
gen1.num_rows

151

In [98]:
gen1.where('is_legendary', 1).num_rows / gen1.num_rows

0.033112582781456956

In [101]:
which_gen = 2
gen = temp.where('generation', which_gen)
gen.where('is_legendary', 1).num_rows / gen.num_rows

0.06

In [102]:
which_gen = 3
gen = temp.where('generation', which_gen)
gen.where('is_legendary', 1).num_rows / gen.num_rows

0.07407407407407407

In [108]:
temp = pokemon.select('name', 'height_m')
temp.show(25)

name,height_m
Bulbasaur,0.7
Ivysaur,1
Venusaur,2
Charmander,0.6
Charmeleon,1.1
Charizard,1.7
Squirtle,0.5
Wartortle,1
Blastoise,1.6
Caterpie,0.3


In [109]:
temp.where('height_m', are.above_or_equal_to(0)).sort('height_m', descending=True).show(5)

name,height_m
Wailord,14.5
Steelix,9.2
Celesteela,9.2
Onix,8.8
Rayquaza,7


In [113]:
temp = pokemon.select('name', 'speed', 'weight_kg').with_column(
    'speed/weight ratio', pokemon.column('speed') / pokemon.column('weight_kg')
)
temp

name,speed,weight_kg,speed/weight ratio
Bulbasaur,45,6.9,6.52174
Ivysaur,60,13,4.61538
Venusaur,80,100,0.8
Charmander,65,8.5,7.64706
Charmeleon,80,19,4.21053
Charizard,100,90.5,1.10497
Squirtle,43,9,4.77778
Wartortle,58,22.5,2.57778
Blastoise,78,85.5,0.912281
Caterpie,45,2.9,15.5172


In [115]:
# nan is short for "not a number". It's a value that is a placeholder for "I don't know"
# you can use .where to get rid of nans
temp.where(3, are.above_or_equal_to(0)).sort(3, descending=True)

name,speed,weight_kg,speed/weight ratio
Kartana,109,0.1,1090
Haunter,95,0.1,950
Gastly,80,0.1,800
Flabébé,42,0.1,420
Cutiefly,84,0.2,420
Azelf,115,0.3,383.333
Cosmog,37,0.1,370
Comfey,100,0.3,333.333
Uxie,95,0.3,316.667
Rotom,86,0.3,286.667


In [117]:
# question: how does the speed of pokemon that are more likely to be female
# compare to the speed of pokemon that are more likely to be male?
temp = pokemon.select('name', 'percentage_male', 'speed')
temp

name,percentage_male,speed
Bulbasaur,88.1,45
Ivysaur,88.1,60
Venusaur,88.1,80
Charmander,88.1,65
Charmeleon,88.1,80
Charizard,88.1,100
Squirtle,88.1,43
Wartortle,88.1,58
Blastoise,88.1,78
Caterpie,50,45


In [119]:
temp = temp.with_column('percentage_female', 100 - temp.column('percentage_male'))
temp

name,percentage_male,speed,percentage_female
Bulbasaur,88.1,45,11.9
Ivysaur,88.1,60,11.9
Venusaur,88.1,80,11.9
Charmander,88.1,65,11.9
Charmeleon,88.1,80,11.9
Charizard,88.1,100,11.9
Squirtle,88.1,43,11.9
Wartortle,88.1,58,11.9
Blastoise,88.1,78,11.9
Caterpie,50,45,50


In [120]:
temp.where('percentage_female', are.above(50))

name,percentage_male,speed,percentage_female
Nidoran♀,0,41,100
Nidorina,0,56,100
Nidoqueen,0,76,100
Clefairy,24.6,35,75.4
Clefable,24.6,60,75.4
Vulpix,24.6,65,75.4
Ninetales,24.6,109,75.4
Jigglypuff,24.6,20,75.4
Wigglytuff,24.6,45,75.4
Chansey,0,50,100


In [122]:
temp.where('percentage_female', are.above(50)).column('speed').mean()

66.79245283018868

In [123]:
temp.where('percentage_male', are.above(50)).column('speed').mean()

68.953020134228183

---

In [5]:
cereal = Table.read_table('data/cereal.csv')
cereal.show(15)

name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.403
100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.9837
All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.4255
All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.7049
Almond Delight,R,C,110,2,2,200,1,14,8,-1,25,3,1,0.75,34.3848
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1,0.75,29.5095
Apple Jacks,K,C,110,2,0,125,1,11,14,30,25,2,1,1,33.1741
Basic 4,G,C,130,3,2,210,2,18,8,100,25,3,1.33,0.75,37.0386
Bran Chex,R,C,90,2,1,200,4,15,6,125,25,1,1,0.67,49.1203
Bran Flakes,P,C,90,3,0,210,5,13,5,190,25,3,1,0.67,53.3138


In [9]:
cereal.sort('weight', descending=True)

name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
Mueslix Crispy Blend,K,C,160,3,2,150,3,17,13,160,25,3,1.5,0.67,30.3134
Total Raisin Bran,G,C,140,3,1,190,4,15,14,230,100,3,1.5,1,28.5928
Basic 4,G,C,130,3,2,210,2,18,8,100,25,3,1.33,0.75,37.0386
Fruitful Bran,K,C,120,3,0,240,5,14,12,190,25,3,1.33,0.67,41.0155
Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3,21,7,130,25,3,1.33,0.67,40.6923
Post Nat. Raisin Bran,P,C,120,3,1,200,6,11,14,260,25,3,1.33,0.67,37.8406
Raisin Bran,K,C,120,3,1,210,5,14,12,240,25,2,1.33,0.75,39.2592
Just Right Fruit & Nut,K,C,140,3,1,170,2,20,9,95,100,3,1.3,0.75,36.4715
Fruit & Fibre Dates; Walnuts; and Oats,P,C,120,3,2,160,5,12,10,200,25,3,1.25,0.67,40.917
Oatmeal Raisin Crisp,G,C,130,3,2,170,1.5,13.5,10,120,25,3,1.25,0.5,30.4508


In [13]:
cereal.where('name', are.containing('Bran')).column('fiber').mean()

5.7307692307692308

In [14]:
cereal.where('name', are.not_containing('Bran')).column('fiber').mean()

1.425

In [17]:
calories_per_cup = cereal.column('calories') / cereal.column('cups')
cereal.select('name', 'calories', 'cups').with_column(
    'calories per cup', calories_per_cup
).sort(3, descending=True)

name,calories,cups,calories per cup
Grape-Nuts,110,0.25,440
Great Grains Pecan,120,0.33,363.636
Oatmeal Raisin Crisp,130,0.5,260
Mueslix Crispy Blend,160,0.67,238.806
Clusters,110,0.5,220
Cracklin' Oat Bran,110,0.5,220
100% Bran,70,0.33,212.121
All-Bran,70,0.33,212.121
Nutri-Grain Almond-Raisin,140,0.67,208.955
Quaker Oat Squares,100,0.5,200


In [21]:
cereal.where('shelf', are.equal_to(1)).column('rating').mean()

46.145438749999997

In [22]:
cereal.where('shelf', are.equal_to(2)).column('rating').mean()

34.97282652380953

In [23]:
cereal.where('shelf', are.equal_to(3)).column('rating').mean()

45.220032000000003

In [24]:
shelf_1 = cereal.where('shelf', are.equal_to(1))
shelf_1

name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1,0.75,29.5095
Bran Chex,R,C,90,2,1,200,4,15,6,125,25,1,1,0.67,49.1203
Cheerios,G,C,110,6,2,290,2,17,1,105,25,1,1,1.25,50.765
Corn Chex,R,C,110,2,0,280,0,22,3,25,25,1,1,1,41.445
Corn Flakes,K,C,100,2,0,290,1,21,2,35,25,1,1,1,45.8633
Frosted Flakes,K,C,110,1,0,200,1,14,11,25,25,1,1,0.75,31.436
Golden Crisp,P,C,100,2,0,45,0,11,15,40,25,1,1,0.88,35.2524
Honey Nut Cheerios,G,C,110,3,1,250,1.5,11.5,10,90,25,1,1,0.75,31.0722
Honey-comb,P,C,110,1,0,180,0,14,11,35,25,1,1,1.33,28.7424
Multi-Grain Cheerios,G,C,100,2,1,220,2,15,6,90,25,1,1,1,40.106


In [25]:
shelf_1.column('sugars').mean()

4.7999999999999998

In [26]:
cereal.where('shelf', are.equal_to(2)).column('sugars').mean()

9.6190476190476186

In [27]:
cereal.where('shelf', are.equal_to(3)).column('sugars').mean()

6.5277777777777777

In [30]:
cold_vs_hot = cereal.select('name', 'type', 'protein', 'fiber')
cold_vs_hot

name,type,protein,fiber
100% Bran,C,4,10
100% Natural Bran,C,3,2
All-Bran,C,4,9
All-Bran with Extra Fiber,C,4,14
Almond Delight,C,2,1
Apple Cinnamon Cheerios,C,2,1.5
Apple Jacks,C,2,1
Basic 4,C,3,2
Bran Chex,C,2,4
Bran Flakes,C,3,5


In [33]:
# what is the avg. amount of protein in the hot cereals in the dataset?
cold_vs_hot.where('type', are.equal_to('H')).column('protein').mean()

4.0

In [35]:
cold_vs_hot.where('type', are.equal_to('H')).column('fiber').mean()

1.2333333333333334

In [34]:
cold_vs_hot.where('type', are.equal_to('C')).column('protein').mean()

2.4864864864864864

In [36]:
cold_vs_hot.where('type', are.equal_to('C')).column('fiber').mean()

2.189189189189189

In [39]:
cereal.select('name', 'sugars', 'fiber').sort('sugars').show()

name,sugars,fiber
Quaker Oatmeal,-1,2.7
All-Bran with Extra Fiber,0,14
Cream of Wheat (Quick),0,1
Puffed Rice,0,0
Puffed Wheat,0,1
Shredded Wheat,0,3
Shredded Wheat 'n'Bran,0,4
Shredded Wheat spoon size,0,3
Cheerios,1,2
Corn Flakes,2,1


In [40]:
titanic = Table.read_table('data/titanic.csv')
titanic

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,nan,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,nan,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,nan,S
6,0,3,"Moran, Mr. James",male,nan,0,0,330877,8.4583,nan,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,nan,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,nan,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,nan,C


In [43]:
first_class = titanic.where('Pclass', are.equal_to(1))
first_class.where('Sex', are.equal_to('female')).num_rows / first_class.num_rows

0.4351851851851852

In [44]:
second_class = titanic.where('Pclass', are.equal_to(2))
second_class.where('Sex', are.equal_to('female')).num_rows / second_class.num_rows

0.41304347826086957

In [45]:
third_class = titanic.where('Pclass', are.equal_to(3))
third_class.where('Sex', are.equal_to('female')).num_rows / third_class.num_rows

0.29327902240325865

In [46]:
titanic

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,nan,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,nan,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,nan,S
6,0,3,"Moran, Mr. James",male,nan,0,0,330877,8.4583,nan,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,nan,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,nan,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,nan,C


In [50]:
titanic.where('Sex', 'male').column('Survived').mean()

0.18890814558058924

In [53]:
titanic.where('Sex', 'male').where('Survived', 1).num_rows

109

In [54]:
titanic.where('Sex', 'male').num_rows

577

In [55]:
109 / 577

0.18890814558058924

In [56]:
titanic.where('Sex', 'female').column('Survived').mean()

0.7420382165605095

In [59]:
titanic.where('Age', are.between_or_equal_to(0, 17)).column('Survived').mean()

0.53982300884955747

In [60]:
titanic.where('Age', are.between_or_equal_to(18, 30)).column('Survived').mean()

0.35472972972972971

In [61]:
titanic.where('Age', are.above(30)).column('Survived').mean()

0.40655737704918032

In [64]:
titanic.column('Fare').mean() # average is probably weighted too high

32.204207968574636

In [65]:
titanic.where('Pclass', 3).column('Fare').mean()

13.675550101832993

In [68]:
titanic.where('Pclass', 2).column('Fare').mean() # probably the best price to compare against

20.662183152173913

In [67]:
titanic.where('Pclass', 1).column('Fare').mean()

84.154687499999994

In [70]:
titanic.where('Fare', are.above(20)).column('Survived').mean()

0.5292553191489362

In [71]:
titanic.where('Fare', are.not_above(20)).column('Survived').mean()

0.27766990291262134

In [72]:
titanic.where('Pclass', 3).column('Survived').mean()

0.24236252545824846

In [73]:
titanic.where('Pclass', 2).column('Survived').mean()

0.47282608695652173

In [74]:
titanic.where('Pclass', 1).column('Survived').mean()

0.62962962962962965

In [75]:
titanic.where('Survived', 1).sort('Fare')

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0,nan,S
805,1,3,"Hedman, Mr. Oskar Arvid",male,27,0,0,347089,6.975,nan,S
128,1,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.1417,nan,S
20,1,3,"Masselmani, Mrs. Fatima",female,nan,0,0,2649,7.225,nan,C
554,1,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22,0,0,2620,7.225,nan,C
876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15,0,0,2667,7.225,nan,C
37,1,3,"Mamee, Mr. Hanna",male,nan,0,0,2677,7.2292,nan,C
368,1,3,"Moussa, Mrs. (Mantoura Boulos)",female,nan,0,0,2626,7.2292,nan,C
763,1,3,"Barah, Mr. Hanna Assi",male,20,0,0,2663,7.2292,nan,C
781,1,3,"Ayoub, Miss. Banoura",female,13,0,0,2687,7.2292,nan,C


In [76]:
titanic.where('Survived', 1).sort('Fare', descending=True)

PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.329,nan,C
680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.329,B51 B53 B55,C
738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.329,B101,C
89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263,C23 C25 C27,S
342,1,1,"Fortune, Miss. Alice Elizabeth",female,24,3,2,19950,263,C23 C25 C27,S
312,1,1,"Ryerson, Miss. Emily Borie",female,18,2,2,PC 17608,262.375,B57 B59 B63 B66,C
743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21,2,2,PC 17608,262.375,B57 B59 B63 B66,C
300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50,0,1,PC 17558,247.521,B58 B60,C
381,1,1,"Bidois, Miss. Rosalie",female,42,0,0,PC 17757,227.525,nan,C
701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18,1,0,PC 17757,227.525,C62 C64,C


In [77]:
temps = Table.read_table('data/max-min-temperatures-fresno-up-to-2025.csv')
temps

Date,Highest High,Highest High Year,Lowest Low,Lowest Low Year
01/01,69,1998,21,1976
01/02,70,1948,20,1976
01/03,72,1948,23,1976
01/04,71,1948,22,1976
01/05,72,2018,20,1949
01/06,73,1948,17,1913
01/07,71,1911,20,1913
01/08,72,1911,22,1888
01/09,70,1953,23,1949
01/10,68,2025,18,1949


In [78]:
january = temps.where('Date', are.containing('01/'))
january

Date,Highest High,Highest High Year,Lowest Low,Lowest Low Year
01/01,69,1998,21,1976
01/02,70,1948,20,1976
01/03,72,1948,23,1976
01/04,71,1948,22,1976
01/05,72,2018,20,1949
01/06,73,1948,17,1913
01/07,71,1911,20,1913
01/08,72,1911,22,1888
01/09,70,1953,23,1949
01/10,68,2025,18,1949


In [81]:
january.column('Highest High').max() - january.column('Lowest Low').min()

61

In [83]:
temps.column('Highest High Year').mean()

1969.8825136612022

In [84]:
temps.column('Lowest Low Year').mean()

1944.016393442623

In [86]:
temps.sort('Highest High Year', descending=True)

Date,Highest High,Highest High Year,Lowest Low,Lowest Low Year
01/10,68,2025,18,1949
01/29,77,2024,24,1902
01/30,74,2024,25,1946
06/06,107,2024,46,1954
07/03,110,2024,50,1901
07/06,112,2024,50,1955
07/07,114,2024,53,1903
07/12,112,2024,54,1965
09/24,103,2024,46,1945
10/02,102,2024,40,1891


In [89]:
temps.where('Highest High Year', are.above_or_equal_to(2000)).num_rows

133

In [90]:
# what was the average lowest low for January dates
temps.where('Date', are.containing('01/')).column('Lowest Low').mean()

22.0

In [91]:
import numpy as np

In [92]:
'hi' * 32

'hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi'

In [95]:
'#' * 70

'######################################################################'

In [100]:
widths = np.round(temps.column('Highest High') / 3).astype(int)
widths

array([23, 23, 24, 24, 24, 24, 24, 24, 23, 23, 25, 22, 23, 23, 25, 24, 25,
       23, 24, 24, 24, 23, 24, 26, 25, 24, 23, 26, 26, 25, 25, 24, 25, 26,
       26, 25, 25, 26, 25, 26, 25, 26, 27, 27, 26, 26, 27, 28, 28, 26, 27,
       26, 26, 26, 26, 27, 28, 26, 28, 26, 26, 27, 27, 28, 28, 29, 28, 28,
       29, 27, 29, 28, 28, 29, 30, 29, 30, 29, 29, 30, 29, 28, 30, 30, 30,
       29, 30, 28, 29, 30, 30, 30, 29, 30, 29, 31, 31, 31, 32, 32, 32, 32,
       32, 32, 33, 32, 32, 31, 32, 31, 32, 33, 32, 33, 34, 34, 33, 33, 33,
       32, 33, 34, 34, 33, 33, 33, 33, 34, 34, 34, 33, 33, 34, 34, 34, 34,
       34, 35, 34, 34, 34, 35, 35, 34, 34, 34, 34, 35, 36, 36, 36, 37, 35,
       35, 36, 35, 36, 36, 36, 36, 37, 35, 35, 36, 36, 36, 36, 37, 36, 37,
       37, 37, 37, 36, 36, 37, 37, 36, 37, 36, 37, 37, 38, 37, 37, 37, 37,
       37, 38, 38, 38, 37, 38, 37, 37, 37, 37, 37, 38, 37, 37, 37, 37, 37,
       38, 38, 38, 38, 38, 37, 38, 38, 38, 37, 37, 37, 37, 37, 37, 37, 38,
       37, 37, 38, 37, 37

In [103]:
bars = np.char.multiply('#', widths)
bars

array(['#######################', '#######################',
       '########################', '########################',
       '########################', '########################',
       '########################', '########################',
       '#######################', '#######################',
       '#########################', '######################',
       '#######################', '#######################',
       '#########################', '########################',
       '#########################', '#######################',
       '########################', '########################',
       '########################', '#######################',
       '########################', '##########################',
       '#########################', '########################',
       '#######################', '##########################',
       '##########################', '#########################',
       '#########################', '##################

In [106]:
temps.select('Date', 'Highest High').with_column('Highest High Graph', bars).show()

Date,Highest High,Highest High Graph
01/01,69,#######################
01/02,70,#######################
01/03,72,########################
01/04,71,########################
01/05,72,########################
01/06,73,########################
01/07,71,########################
01/08,72,########################
01/09,70,#######################
01/10,68,#######################
